apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  # type: LoadBalancer
  type: NodePort  
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 80
    NodePort: 30000
    name: http
