---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  label:
    name: react-frontend
spec:
  selector:
    matchLabels:
      app: react-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: my-app-container
        image: rudreshayd/darshimage:v1.1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "128m"
          limits:
            memory: "250Mi"
            cpu: "256m"
        readinessProbe:
          httpGet: 
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
...