name: Secret and Environment Variable Workflow

on:
  workflow_dispatch:

jobs:
    staging_environment:
        runs-on: ubuntu-latest
        environment: staging
        env:
            EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
            EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE}}
            
            EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE}}
        
        steps:
            - name: Inspect  values inside job
              run: |
                  echo "EXAMPLE_REPOSITORY_SECRET: $EXAMPLE_REPOSITORY_SECRET"
                  echo "EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE: $EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE"
                  echo "EXAMPLE_ENVIRONMENT_SECRET: $EXAMPLE_ENVIRONMENT_SECRET"
                  echo "EXAMPLE_ENVIRONMENT_VARIABLE: $EXAMPLE_ENVIRONMENT_VARIABLE"
    
    production_environment:
        runs-on: ubuntu-latest
        environment: production
        env:
            EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
            EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE}}
            
            EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE}}
        
        steps:
            - name: Inspect  values inside job
              run: |
                  echo "EXAMPLE_REPOSITORY_SECRET: $EXAMPLE_REPOSITORY_SECRET"
                  echo "EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE: $EXAMPLE_REPOSITORY_ENVIRONMENT_VARIABLE"
                  echo "EXAMPLE_ENVIRONMENT_SECRET: $EXAMPLE_ENVIRONMENT_SECRET"
                  echo "EXAMPLE_ENVIRONMENT_VARIABLE: $EXAMPLE_ENVIRONMENT_VARIABLE"